# Generated by Django 2.2.6 on 2019-10-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
