# Generated by Django 2.2.6 on 2019-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
