# Generated by Django 2.2.6 on 2019-10-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
