# Generated by Django 2.2.6 on 2019-11-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='review/static/game_images/')),
                ('title', models.TextField(max_length=120)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
