# Generated by Django 2.2.6 on 2019-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_path',
            field=models.ImageField(upload_to='game_images/'),
        ),
    ]
