# Generated by Django 2.2.6 on 2019-10-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='picname',
            field=models.CharField(default='nan', max_length=50),
        ),
    ]
