# Generated by Django 2.2.6 on 2019-10-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191019_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_path',
            field=models.ImageField(upload_to='review/static/game_images/'),
        ),
    ]
