# Generated by Django 2.2.6 on 2019-10-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191017_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='not', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='picname',
            field=models.CharField(default='nan', max_length=50),
        ),
    ]
