# Generated by Django 2.2.6 on 2019-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20191018_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='game',
            name='picname',
        ),
        migrations.AddField(
            model_name='game',
            name='image_path',
            field=models.TextField(default='non', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.TextField(default='non', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='ab', max_length=50),
        ),
    ]
