# Generated by Django 2.2.6 on 2019-10-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191018_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_path',
            field=models.TextField(default='ab', max_length=50),
        ),
    ]
