# Generated by Django 2.2.6 on 2019-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playthroughs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100)),
                ('playthroughTitle', models.CharField(max_length=100)),
                ('playDescription', models.TextField()),
            ],
        ),
    ]
