# Generated by Django 2.2.6 on 2019-11-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playthroughs', '0003_auto_20191107_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playthrough_comment',
            name='on_playthrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playthroughs.Playthroughs'),
        ),
    ]
