# Generated by Django 2.2.6 on 2019-11-08 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playthroughs', '0005_auto_20191107_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playthrough_comment',
            name='on_playthrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playthroughs.Playthroughs'),
        ),
    ]
