# Generated by Django 2.2.6 on 2019-11-08 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playthroughs', '0006_auto_20191108_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
