# Generated by Django 2.2.6 on 2019-10-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_path',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_mime_type',
        ),
    ]
