# Generated by Django 2.2.6 on 2019-12-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned_from_posting',
            field=models.BooleanField(default=False),
        ),
    ]
