# Generated by Django 2.2.6 on 2019-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_banned_from_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
            ],
        ),
    ]
